import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import DesktopNavbar from '@/components/DesktopNavbar';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navItems = [
    {
      name: 'Home',
      link: '/',
    },
    {
      name: 'Pricing',
      link: '/pricing',
    },
    {
      name: 'Contact',
      link: '/contact',
    },
    {
      name: 'Portfolio',
      link: '/portfolio',
    },
  ];
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar navItems={navItems} />
        <DesktopNavbar navItems={navItems} />
        {children}
      </body>
    </html>
  );
}
